name: 헤로쿠 테스트 배포

on:
  push:
    branches:
      - release

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 프로젝트 체크아웃
        uses: actions/checkout@v2

      - name: Node.js 사용
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'

      - name: Heroku CLI 설치
        run: curl https://cli-assets.heroku.com/install.sh | sh

      - name: 의존성 설치
        run: yarn

      - name: 프로젝트 빌드
        run: yarn build

      - name: Heroku에 로그인
        run: heroku login -i <<< "${{ secrets.HEROKU_API_KEY}}"

      - name: Heroku 앱에 연결
        run: heroku git:remote -a weeklybest-backend

      - name: Heroku 배포
        run: git push heroku HEAD:master
