name: 클라우드타입 테스트 배포
on:
  push:
    branches:
      - release
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Connect deploy key
        uses: cloudtype-github-actions/connect@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          ghtoken: ${{ secrets.GHP_TOKEN }}
      - name: Deploy
        uses: cloudtype-github-actions/deploy@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          project: marshot9420/weeklybest
          stage: release
          yaml: |
            name: weeklybest-backend
            app: node@18
            options:
              env:
                - name: NODE_ENV
                  var: node-env
                - name: PORT
                  secret: weeklybest-port
                - name: ADMIN_USER
                  secret: weeklybest-admin-user
                - name: ADMIN_PASSWORD
                  secret: weeklybest-admin-password
                - name: DB_HOST
                  secret: db-host
                - name: DB_PORT
                  secret: db-port
                - name: DB_DATABASE
                  secret: db-weeklybest
                - name: DB_USERNAME
                  secret: db-username
                - name: DB_PASSWORD
                  secret: db-password
                - name: COOKIE_SECRET
                  secret: weeklybest-cookie-secret
              build: yarn build
              start: yarn start:prod
              install: yarn
            context:
              git:
                url: git@github.com:${{ github.repository }}.git
                ref: ${{ github.ref }}
              preset: nest.js
